# Generated by Django 2.1.3 on 2018-12-01 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.TextField()),
                ('tel_num', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Request_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.DecimalField(decimal_places=0, max_digits=4, primary_key='True', serialize=False)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite')], default='SINGLE', max_length=10)),
                ('status_clean', models.CharField(choices=[('CLEAN', 'Clean'), ('UNCLEAN', 'Unclean')], default='CLEAN', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='request_post',
            name='room_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
    ]
