# Generated by Django 2.1.3 on 2018-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_post',
            name='handle_or_not',
            field=models.CharField(default='UNASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='tel_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request_post',
            name='title',
            field=models.TextField(),
        ),
    ]
