# Generated by Django 2.1.3 on 2018-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_room_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='status_clean',
            field=models.IntegerField(choices=[('0', 'Clean'), ('1', 'Unclean')], default='0'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.DecimalField(decimal_places=0, max_digits=4, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[('1', 'Single'), ('2', 'Double'), ('3', 'Suite')], default='1'),
        ),
    ]
