# Generated by Django 2.1.3 on 2018-12-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20181201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_post',
            name='handle_or_not',
            field=models.CharField(choices=[('DONE', '처리완료'), ('NOT_YET', '처리중'), ('UNASSIGNED', '미배정')], default='UNASSIGNED', max_length=20),
        ),
    ]
