# Generated by Django 2.1.3 on 2018-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20181128_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status_clean',
            field=models.CharField(choices=[('CLIAN', 'Clean'), ('UNCLEAN', 'Unclean')], default='CLEAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(default='SINGLE', max_length=10),
        ),
    ]
