# Generated by Django 2.1.3 on 2018-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20181128_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status_clean',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('UNCLEAN', 'Unclean')], default='CLEAN', max_length=10),
        ),
    ]
