# Generated by Django 2.1.3 on 2018-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=15)),
                ('introduction', models.TextField()),
            ],
        ),
    ]
