# Generated by Django 2.1.3 on 2018-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=10)),
                ('guest_pw', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('phone_num', models.CharField(max_length=13)),
                ('e_mail', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=20)),
                ('guest_class', models.CharField(max_length=10)),
            ],
        ),
    ]
